# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'EAColourfulProgressViewExample' do

pod ‘Masonry’

end

target 'EAColourfulProgressViewExampleTests' do

end

